create table users
(
    id bigint generated by default as identity constraint users_pkey primary key,
    created  timestamp with time zone default current_timestamp,
    status   varchar(255) default 'ACTIVE',
    updated  timestamp with time zone default current_timestamp,
    email    varchar(255),
    password varchar(255),
    username varchar(255)
);

create table roles
(
    id bigint generated by default as identity constraint roles_pkey primary key,
    created timestamp with time zone default current_timestamp,
    status  varchar(255) default 'ACTIVE',
    updated timestamp with time zone default current_timestamp,
    name varchar(255)
);

create table user_roles
(
    id bigint generated by default as identity,
    user_id bigint not null,
    role_id bigint not null,
    primary key (id),
    foreign key (user_id) references users,
    foreign key (role_id) references roles
);

alter table users
    owner to postgres;

alter table roles
    owner to postgres;

alter table user_roles
    owner to postgres;
