create table ohcl
(
    id               bigint generated by default as identity
        constraint btc_usd_pkey
            primary key,
    created          timestamp,
    status           varchar(255),
    updated          timestamp,
    close            double precision,
    foreign_notional double precision,
    high             double precision,
    home_notional    double precision,
    last_size        double precision,
    low              double precision,
    open             double precision,
    symbol           varchar(255),
    timestamp        varchar(255),
    trades           double precision,
    turnover         double precision,
    volume           double precision,
    vwap             double precision
);

alter table ohcl
    owner to postgres;